<!DOCTYPE html>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<html lang="en">

<body>
    <h1>${message}</h1>

    <p><a href="${springUrl}">URL generated by Spring</a></p>
    <p><a href="${url}">URL generated by JSTL</a></p>
    <form method = "GET" action = "/signup">
	 <input type = "submit" value = "SignUp"/>
	 </form>
	  <form method = "GET" action = "/login">
	 <input type = "submit" value = "Login"/>
	 </form>
</body>

</html>